import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Awesome Site!',
  description: 'Generated by create Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>
        <header>
          <Link href="/" className='bg-gradient-to-r from-pink-500 via-blue-300 to-violet-500 bg-clip-text text-transparent text-lg font-extrabold'>
            Home
          </Link>
        </header>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
